# Generated by Django 4.1.1 on 2022-10-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="autores",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="editora",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="preco",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="quantidade",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="titulo",
        ),
        migrations.AddField(
            model_name="livro",
            name="capa",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="media.image",
            ),
        ),
    ]
