# Generated by Django 4.1.1 on 2022-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_autor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editora",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
    ]
