# Generated by Django 4.1.1 on 2022-10-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_livro_autores_livro_categoria_livro_editora_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="isbn",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
